# Generated by Django 3.2.3 on 2021-05-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbNail',
            new_name='thumbnail',
        ),
    ]
