# Generated by Django 3.1.7 on 2021-05-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20210514_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_pic',
            field=models.ImageField(default='', upload_to='authors/<django.db.models.query_utils.DeferredAttribute object at 0x0000022ACA295970>'),
        ),
    ]
