# Generated by Django 3.2.3 on 2021-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20210514_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
