# Generated by Django 3.2.3 on 2021-05-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_profile_display_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_pic',
        ),
    ]
