# Generated by Django 3.2.3 on 2021-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_remove_profile_display_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_pic',
            field=models.FileField(default='', upload_to='pic_folder'),
        ),
    ]
