# Generated by Django 3.2.3 on 2021-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_profile_display_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_pic',
            field=models.FileField(upload_to='pic_folder/<django.db.models.query_utils.DeferredAttribute object at 0x000001EFB9DBE970>'),
        ),
    ]
