# Generated by Django 3.2.3 on 2021-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_alter_profile_display_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder'),
        ),
    ]
