# Generated by Django 3.2.3 on 2021-05-22 17:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_profile_display_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[100, 100], upload_to='pic_folder'),
        ),
    ]
