# Generated by Django 3.2.3 on 2021-06-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
