# Generated by Django 3.2.3 on 2021-06-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
